/*
-- Query: SELECT * FROM auc_catalog.department
LIMIT 0, 1000

-- Date: 2020-11-12 20:17
*/
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ACCT','Accounting');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('AIAS','Chemistry');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ALIN','Arabic Writing');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ALIS','Architectural Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ALNG','Arabic Language Intensive');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ALWT','Arabic Language Intensive Summer');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('AMST','American Studies');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ANTH','Anthropology');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('APLN','Applied Linguistics');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ARCH','Biology');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ARIC','Arabic Language');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ARTV','Visual Arts');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('BADM','Business School');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('BIOL','Biotechnology');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('BIOT','Business Administration');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('BUSC','Center For Arabic Studies Abroad');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('CEMS','Linguistics');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('CENG','Data Science');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('CHEM','Comparative Religion');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('CORE','Economics');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('CREL','Construction Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('CSCE','Core Curriculum');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('DSCI','Egyptology');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('DSGN','International Human Rights Law');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ECLT','Film');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ECNG','English & Comparative Literature');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ECON','Electronics and Communications Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('EDUC','Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('EGPT','English');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ELIN','Environmental Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('EMBA','Global Public Health');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ENGL','Executive Business Administration');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ENGR','Entrepreneurship');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ENTR','Finance');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('ENVE','Gender and Women’s Studies');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('FILM','Graphic Design');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('FINC','History');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('GHHE','International Business');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('GREN','Sustainable Development');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('GWST','Intensive English');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('HIST','International Management');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('INTB','Journalism & Mass Communication');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('JRMC','LAW');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('LALT','Management');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('LAW','Libraries and Learning Technologies');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('LING','Arab and Islamic Civilizations');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MACT','Mechanical Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MENG','Middle East Studies');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MEST','Migration & Refugee Studies');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MGMT','Management of Information Systems');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MKTG','Mathematics and Actuarial Science');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MOIS','Marketing');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MRS','Music');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('MUSC','Nanotechnology');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('NANO','Operations Management');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('OPMG','Petroleum Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('PENG','Ph.D. in Applied Sciences');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('PHDE','Philosophy');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('PHDS','Ph.D. in Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('PHIL','Physics');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('PHYS','Political Science');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('POLS','Production /Operations Management');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('PPAD','Public Policy and Administration');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('PSYC','Psychology');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('RCSS','Robotics, Control and Smart Systems');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('RHET','Rhetoric and Composition');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('SCI','Computer Science and Engineering');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('SEMR','Education');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('SOC','Sociology');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('TEAL','Teaching & Learning');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('THTR','Theatre');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('TRST','Translation Studies');
INSERT INTO `` (`DeptCode`,`DeptName`) VALUES ('TVDJ','Television and Digital Journalism');
